name: test-google-sheets-access

on:
  workflow_dispatch:

jobs:
  test-google-sheets:
    runs-on: ubuntu-latest
    steps:
      - name: Test Access to Google Sheets
        uses: ViRGiL175/github-project-issue-to-sheets@dev
        with:
          google-api-service-account-credentials: ${{ secrets.GOOGLE_SHEET_CREDENTIALS }}
          document-id: '1atfohlYVp6LcswuRapXt6Xf5GJmEH2OXo8mESezyPQc'
          sheet-name: 'test'
          github-token: ${{ secrets.TOKEN }}
